# Generated by Django 5.0.7 on 2024-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRS',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
                ('field3', models.TextField()),
                ('field4', models.TextField()),
                ('field5', models.TextField()),
            ],
            options={
                'db_table': 'tbl_srs',
            },
        ),
    ]
