# Generated by Django 5.0.7 on 2024-08-20 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_srs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('overall_experience', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('ease_of_use', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Neutral', 'Neutral'), ('Difficult', 'Difficult'), ('Very Difficult', 'Very Difficult')], max_length=20)),
                ('functionality', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('visual_design', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20)),
                ('performance', models.CharField(choices=[('Very Fast', 'Very Fast'), ('Fast', 'Fast'), ('Average', 'Average'), ('Slow', 'Slow'), ('Very Slow', 'Very Slow')], max_length=20)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
