<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-20 18:51
=======
# Generated by Django 5.0.7 on 2024-08-20 15:44
>>>>>>> cac796c0bedfcf244549c761cf72aebc1555d4d3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('report', models.TextField()),
                ('file', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_support',
            },
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
